- name: update ipset country bans
  hosts: ipset_country

  vars:

    ansible_no_target_syslog: true

  vars_files:

    - vars.yaml

  tasks:

    - apt:
        name:
          - ipset
          - iptables
      become: true

    - copy:
        src: "../ipset-{{ item }}.txt"
        dest: /root/
        owner: root
        group: root
        mode: "0644"
      loop: "{{ countries }}"
      become: true

    - command:
        chdir: /root
        argv:
          - /sbin/ipset
          - restore
          - -file
          - "ipset-{{ item }}.txt"
      loop: "{{ countries }}"
      become: true

    - iptables:
        chain: INPUT
        ip_version: ipv4
        jump: REJECT
        match: set
        match_set: "country-{{ item }}-v4"
        match_set_flags: src
      loop: "{{ countries }}"
      become: true

    - iptables:
        chain: INPUT
        ip_version: ipv6
        jump: REJECT
        match: set
        match_set: "country-{{ item }}-v6"
        match_set_flags: src
      loop: "{{ countries }}"
      become: true
